config/routes.rb
Yue::Application.routes.draw do
  resources :relationships

  resources :in_app_types

  resources :photos

  resources :albums

  get "images/index"
  get "images/new"
  get "images/show"
  post "images/create"

  get 'test_push' => 'push#index'
  post 'test_push' => 'push#test_push'

  resources :posts

  devise_for :users

  root :to => "home#index"
  

  match '/avatar', to: 'home#avatar', via: 'get'
  match '/avatar', to: 'home#create', via: 'post'

  resources :posts do
    resources :comments
  end

  match '/help',    to: 'home#help',    via: 'get'
  match '/about',   to: 'home#about',   via: 'get'
  match '/contact', to: 'home#contact', via: 'get'
  match '/about_me',   to: 'home#about_me',   via: 'get'

  

  namespace :api do
    namespace :v1 do

      post 'validate' => 'receipts#validate'

      get "rece" => "receipts#v"
      

      post 'online' => 'online#create'

      post 'online/:id/comments' => 'online#comments' 

      post 'message/send' => 'message#sender'
      post 'message/find_by_message' => 'message#find_by_message'
      post 'message/find_by_messageDetail' => 'message#find_by_messageDetail'

      post 'message/readMessage' => 'message#readMessage'
      post 'message/delMessage' => 'message#delMessage'

      get 'populer' => 'online#populer'

      get 'online/my_list' => 'online#my_list' 
      get 'online/new_online' => 'online#new_online' 
      get 'online_detail' => 'online#online_detail' 

      get 'tags' => 'tag#tag_for_keyworld' 

      get 'tag_hot' => 'tag#tag_hot' 

      devise_scope :user do

        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
        
        get "albums" => "album#index"
        post "albums" => "album#index"

        get 'post' => 'post#index', :as => 'post'
        post  'posts' => 'post#index', :as => 'posts'

        get "info" => 'post#info', :as=> 'info'

        post "upload" => 'post#upload', :as => 'upload'

        get "getsp" => "upyun#getsp", :as => "getsp"
        
        get "test" => 'test#index', :as => 'test'
        post 'test' => 'test#test'
        

      end

      get 'tasks' => 'tasks#index', :as => 'tasks'
      post 'tasks' => 'tasks#create'
      put 'tasks/:id/open' => 'tasks#open', :as => 'open_task'
      put 'tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
    end
  end
  
  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  # caches_page :about

  

  
  def index
    HardWorker.perform_async('bob', 5)
    if current_user
      @feed_items = current_user.feed.paginate(:page => params[:page])
      @followers = current_user.followers.paginate(page: params[:page])
      @following = current_user.following.paginate(page: params[:page])
    end

    @posts = Post.all  

  end

  def create 


  	current_user.avatar = params[:avatar]
  	current_user.save

  	render 'avatar'
  end


  def avatar
    @user = current_user

  end

  def about
    
  end

  def about_me
    
  end
  
  def help
  end
  
  
  def contact
  end
end

app/views/home/about.html.erb
<link href="http://v3.bootcss.com/assets/css/docs.min.css" rel="stylesheet">
<div class="jumbotron masthead">
  <div class="container">
    <h1>关于</h1>
    <h3>它是一个聚合类型的站点，作者希望可以把tumblr和instagram的优秀内容聚合并且展现给喜爱他们的用户。</h2>
    <p class="masthead-button-links">
          <%= link_to "关于作者",   about_me_path %>

    </p>
 
  </div>
</div>

app/views/home/about_me.html.erb
<link href="http://v3.bootcss.com/assets/css/docs.min.css" rel="stylesheet">

<h2>介绍</h2>
<ul>
	<li>姓名： 曾辉</li>
	<li>年龄： 25</li>
	<li>城市： 北京 石家庄</li>
	<li>常用 Email： <a href="mailto:zenghui515@foxmail.com">zenghui515@foxmail.com</a> </li>
	<li>Site Email： <a href="mailto:zenghui@yuenvshen.com">zenghui@yuenvshen.com</a></li>	
	<li>Home： <a href="https://www.yuenvshen.com/">https://www.yuenvshen.com/</a></li>
	<li>Github： <a href="https://github.com/zhzenghui">@zhzenghui</a></li>
	<li>Github IO： <a href="http://zhzenghui.github.io">http://zhzenghui.github.io/</a>(暂时还没有有用的内容)</li>
</ul>

<h2>技能</h2>
<ul>
	<li>4年的 Objective-C 开发经验，熟悉iOS OS X的应用开发;</li>
	<li>熟悉OS X, Linux 环境下的开发;</li>
	<li>半年的Linux服务器维护经验（非正式产品）;</li>
	<li>1年的Ruby后端开发经验， 1 年 Asp.NET (C#) 开发经验;</li>
	<li>熟悉 MySQL,SQL Server, Redis 等数据库;</li>
	<li>熟悉 Git, SVN;</li>
	<li>熟悉 HTML、CSS、Javascript</li>
	<li>略懂 UI, UE，熟练使用 Photoshop;</li>
	<li>熟悉 Sublime Text， TextMate;</li>
</ul>

<h2>经历</h2>


<ul>
	<li>2008年在石家庄信息工程职业学院，学习.Net，熟悉Asp.Net的开发和Windows Server的配置。</li>
	<li>2010年10月加入石家庄银康科技实习并正式加入，刚加入时主要适用vb.Net开发工作，在一次工作调动中，进入了iOS开发组，参与enmpass客户端开发。</li>
	<li>2012年2在北京金溪欣，在这里做了一个起亚某款车的App，大部分的时间都在维护和协助其他人员的App开发工作。合同到期后，决定离开。</li>
	<li>2013年5月加入中视博桥，iOS技术负责人，期间做过10多个项目（琨庭，东易日盛（团队），东方百盛，设计师（公司产品），汉诺地板，实创（实小创，设计师，客户）朗斯等多个产品）一直到现在。</li>

</ul>

<h2>work</h2>
<ul>
	<li>作品： <a href="https://file.i-bejoy.com/apps.html">https://file.i-bejoy.com/apps.html</a></li>
	<li>App Store: <a href="https://itunes.apple.com/us/artist/feng-lee/id595313852">https://itunes.apple.com/us/artist/feng-lee/id595313852 （这是公司的账号） </li>

</ul>

app/views/home/avatar.html.erb
<br />
<%= image_tag current_user.avatar.url %> <br />
<%= image_tag current_user.avatar.url(:medium) %> <br />
<%= image_tag current_user.avatar.url(:thumb) %> <br />



<%= form_for avatar_path, :html => {:multipart => true} do |f| %>
  <p>
    <label>My Avatar</label>
    <%= file_field_tag :avatar %>

    <%= f.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
     
		 
		 
<% if signed_in? %>
	   
	<h1>最新动态</h1>

	      <%= render 'shared/feed' %>
	<h1>关注我的</h1>

	<br>
	<br>

	<%  @followers.each do |user|  %>
	      <%= user.id %>
	      <%= user.name %>
	      
	<% end %>

	<br>
	<br>


	<h1>我关注的</h1>

	<br>
	<br>

	<%  @following.each do |user|  %>
	      <%= user.id %>
	      <%= user.name %>
	      
	<% end %>

	<br>
	<br>

<% else %>

      <div class="row">
       
        <div>

          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
   			 <% @posts.each do |post| %>
                <div class="col-xs-6 col-sm-3 placeholder">
                <%= link_to post  do %>
                                  <%= image_tag post.avatar.url(:medium), style:"width: 200; height: 200;", class: "featurette-image img-responsive img-thumbnail" %> 
				<% end -%>
					<p class="lead">
					<ul class="list-unstyled">
						<li > 
						    <span> <h3>  <%= link_to post.title, post %></h3> @<%= link_to post.user.name , posts_path  %></span>

						</li>
						<li>
							<span class="text-muted"><%= post.text %></span>
						</li>
					</ul>

                	</p>

              </div>
	 		 <% end %>

         </div>
	</div>
<% end %>