config/routes.rb
Yue::Application.routes.draw do
  resources :relationships

  resources :in_app_types

  resources :photos

  resources :albums

  get "images/index"
  get "images/new"
  get "images/show"
  post "images/create"

  get 'test_push' => 'push#index'
  post 'test_push' => 'push#test_push'

  resources :posts

  devise_for :users

  root :to => "home#index"
  

  match '/avatar', to: 'home#avatar', via: 'get'
  match '/avatar', to: 'home#create', via: 'post'

  resources :posts do
    resources :comments
  end

  match '/help',    to: 'home#help',    via: 'get'
  match '/about',   to: 'home#about',   via: 'get'
  match '/contact', to: 'home#contact', via: 'get'
  match '/about_me',   to: 'home#about_me',   via: 'get'

  

  namespace :api do
    namespace :v1 do

      post 'validate' => 'receipts#validate'

      get "rece" => "receipts#v"
      

      post 'online' => 'online#create'

      post 'online/:id/comments' => 'online#comments' 

      post 'message/send' => 'message#sender'
      post 'message/find_by_message' => 'message#find_by_message'
      post 'message/find_by_messageDetail' => 'message#find_by_messageDetail'

      post 'message/readMessage' => 'message#readMessage'
      post 'message/delMessage' => 'message#delMessage'

      get 'populer' => 'online#populer'

      get 'online/my_list' => 'online#my_list' 
      get 'online/new_online' => 'online#new_online' 
      get 'online_detail' => 'online#online_detail' 

      get 'tags' => 'tag#tag_for_keyworld' 

      get 'tag_hot' => 'tag#tag_hot' 

      devise_scope :user do

        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
        
        get "albums" => "album#index"
        post "albums" => "album#index"

        get 'post' => 'post#index', :as => 'post'
        post  'posts' => 'post#index', :as => 'posts'

        get "info" => 'post#info', :as=> 'info'

        post "upload" => 'post#upload', :as => 'upload'

        get "getsp" => "upyun#getsp", :as => "getsp"
        
        get "test" => 'test#index', :as => 'test'
        post 'test' => 'test#test'
        

      end

      get 'tasks' => 'tasks#index', :as => 'tasks'
      post 'tasks' => 'tasks#create'
      put 'tasks/:id/open' => 'tasks#open', :as => 'open_task'
      put 'tasks/:id/complete' => 'tasks#complete', :as => 'complete_task'
    end
  end
  
  
  

end

app/views/layouts/_footer.html.erb
<br />

<footer>
  <p class="pull-right"><%= link_to "关于",   about_path %></p>
  <p>© 2014 月 · 京ICP备14025431号 <img src="http://upfiles.b0.upaiyun.com/logo/90x45.png" alt="UPYUN"></p>


</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	        <ul class="nav navbar-nav navbar">
	          <li><%= link_to image_tag(asset_path("logo1.0-48.png"), alt: "logo"), ''%>  </li>
	          <li>	<%= link_to t(:site_name), root_path , class:'navbar-brand' %></li>
     
	        </ul>
        </div>

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
	          <li><%= link_to t(:home), root_path %></li>
	          <li><%= link_to t(:post), posts_path %></li>
<!-- 	          <li><%= link_to t(:albums), albums_path %></li>
	          <li><%= link_to t(:photo), photos_path %></li>
	          <li><%= link_to t(:in_app), in_app_types_path %></li>

	          <li><%= link_to t(:relationships), relationships_path %></li> -->

          </ul>
          <ul class="nav navbar-nav navbar-right">

	          <% if signed_in? %>

	            <li id="fat-menu" class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                <%= current_user.name  %><b class="caret"></b>
	              </a>
	              <ul class="dropdown-menu">
	                <li><%= link_to "我的信息", root_path %></li>
	                <li><%= link_to "设置", edit_user_registration_path(current_user) %></li>
	                <li class="divider"></li>
	                <li>
	                  <%= link_to t(:sign_out), destroy_user_session_path, method: "delete" %>
	                </li>
	              </ul>
	            </li>
	            <li class="dropdown">
            </li>
	          <% else %>
	            <li><%= link_to t(:sign_in),   new_user_session_path %></li>
	          <% end %>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
</div>
<br />

		
	

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>  
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>


    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      		<% flash.each do |key, value| %>
        		<div class="alert alert-<%= key %>"><%= value %></div>
      		<% end %>
		<div class="container">
			<%= yield %>
			
			
      <%= render 'layouts/footer' %>
			
      <%= debug(params) if Rails.env.development? %>
		</div>

    </div>
  </body>
</html>